
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd   
spec:
  project: default
  source:
    repoURL: https://github.com/karlschriek/kyverno-test.git
    targetRevision: master
    path: kyverno
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karl
  namespace: argocd   
spec:
  project: default
  source:
    repoURL: https://github.com/karlschriek/kyverno-test.git
    targetRevision: master
    path: karl
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true