apiVersion: v1
kind: Pod
metadata:
  name: pass
  namespace: karl
spec:
  containers:
  - name: alpine
    image: alpine:3.7
    command:
    - nsenter
    - "--mount=/proc/1/ns/mnt"
    - "--"
    - sh
    - "-"
    stdin: true
    tty: true
    resources:
      requests:
        cpu: 10m
